### ISSUE TITLE
Are NaN values for bca() to be expected?

### ISSUE THREAD

**Issue by t-pollington** [jkropko/coxed#2]
Dear @jkropko ,

Thanks a lot for developing this package. I am currently in the process of incorporating your `coxed::bca()` function into a pull request for the _IDSpatialStats_ package. However I found a strange anomaly when creating unit tests using vectors of ones or zeroes or containing Infs, compared to the base `quantile()` function:

``` r
quantile(c(0,0))
#>   0%  25%  50%  75% 100% 
#>    0    0    0    0    0
coxed::bca(c(0,0))
#>         
#> NaN NaN

quantile(c(1,1))
#>   0%  25%  50%  75% 100% 
#>    1    1    1    1    1
coxed::bca(c(1,1))
#>         
#> NaN NaN

quantile(c(0,Inf))
#>   0%  25%  50%  75% 100% 
#>    0  Inf  Inf  Inf  Inf
coxed::bca(c(0,Inf))
#>         
#> NaN NaN
```

<sup>Created on 2020-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is this a bug or an inherent breakdown in the BCa algorithm?

Kind regards, Tim.

**Comment by jkropko** [comment]
Thank you Tim, I'm looking into it now. Been distracted getting my classes online!

**Comment by t-pollington** [comment]
Ah great @jkropko. Yeah no worries, just getting used to the new structure of the day here in the UK.

**Comment by jkropko** [comment]
added corrections and errors for edge cases with bca() (no variance, infinite values)
